/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.Controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class TelaCadastroPalavra extends javax.swing.JFrame {
    Controlador controlador = new Controlador();

    /**
     * Creates new form TelaCadastroPalavra
     */
    public TelaCadastroPalavra() {
        initComponents();
    }
    
    private void cadastraPalavra(String termo, String definicao, String fonte){
        if (controlador.validaVazio(termo) || termo.length() <= 2) {            
            JOptionPane.showMessageDialog(this, "O TERMO não pode estar vazio ou menor do que 2 caracteres.");
        } else if (controlador.validaIncoerente(termo)){
            JOptionPane.showMessageDialog(this, "O TERMO não pode conter apenas números ou símbolos.");
        } else if(controlador.validaRepetido(termo)){
            JOptionPane.showMessageDialog(this, "Já existe este termo no dicionário.");
        } else if (controlador.validaIncoerente(definicao)) {
            JOptionPane.showMessageDialog(this, "A DEFINIÇÃO não pode conter apenas números ou símbolos.");
        } else if (controlador.validaVazio(definicao)|| definicao.length() <= 20){
            JOptionPane.showMessageDialog(this, "A DEFINIÇÃO não pode estar vazia ou menor que 20 caracteres.");        
        } else if (controlador.validaVazio(fonte) || fonte.length() <= 20){
            JOptionPane.showMessageDialog(this, "A FONTE não pode estar vazia ou menor que 20 caracteres.");   
        } else if (controlador.validaIncoerente(fonte)){
            JOptionPane.showMessageDialog(this, "A FONTE pode conter apenas números ou símbolos.");   
        } else {
            controlador.cadastraNovaPalavra(controlador.mudaPontoEVirgula(termo), controlador.mudaPontoEVirgula(definicao), controlador.mudaPontoEVirgula(fonte));
            JOptionPane.showMessageDialog(this, "Termo cadastrado com sucesso!");
            dispose();
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTermo = new javax.swing.JLabel();
        txtTermo = new javax.swing.JTextField();
        lblDefinicao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDefinicao = new javax.swing.JTextArea();
        lblFonte = new javax.swing.JLabel();
        txtFonte = new javax.swing.JTextArea();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de novo Termo | Dicionário de Gestão");
        setAlwaysOnTop(true);
        setResizable(false);

        lblTermo.setText("Termo:");

        lblDefinicao.setText("Definição");

        txtDefinicao.setColumns(20);
        txtDefinicao.setRows(5);
        jScrollPane2.setViewportView(txtDefinicao);

        lblFonte.setText("Fonte");

        txtFonte.setColumns(20);
        txtFonte.setRows(5);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTermo)
                    .addComponent(jScrollPane2)
                    .addComponent(txtFonte)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTermo)
                            .addComponent(lblDefinicao)
                            .addComponent(lblFonte))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTermo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTermo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDefinicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFonte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtTermo.setText("");
        txtDefinicao.setText("");
        txtFonte.setText("");        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastraPalavra(txtTermo.getText(), txtDefinicao.getText(), txtFonte.getText());
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPalavra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDefinicao;
    private javax.swing.JLabel lblFonte;
    private javax.swing.JLabel lblTermo;
    private javax.swing.JTextArea txtDefinicao;
    private javax.swing.JTextArea txtFonte;
    private javax.swing.JTextField txtTermo;
    // End of variables declaration//GEN-END:variables
}
